name: temperatureconverter
version: 0.0.1
description: a temperature converter
author: Thomas Kuenneth <thomas@thomaskuenneth.com>
homepage: https://www.thomaskuenneth.com
dependencies:
  intl: ^0.14.0