name: temperatureconverter
version: 0.0.2
description: a temperature converter
author: Thomas Kuenneth <thomas@thomaskuenneth.com>
homepage: https://www.thomaskuenneth.com
dependencies:
  intl: ^0.15.8

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0